### ISSUE TITLE
请问还传ESPnet的训练代码吗？

### ISSUE THREAD

**Issue by heyi-core** [TencentGameMate/chinese_speech_pretrain#8]

**Comment by pengchengguo** [comment]
你好，稍作整理后会上传上去。ESPnet 中已支持将预训练模型作为 frontend 进行特征提取，然后输入 Conformer ASR 模型的训练。可以在 Aishell Conformer 配置文件中添加
```
freeze_param: [
"frontend.upstream"
]

frontend: s3prl
frontend_conf:
    frontend_conf:
        upstream: hubert_local
        upstream_model_config:
        upstream_ckpt: ${YOUR_PATH}/checkpoint_best.pt
    download_dir: ./hub
    multilayer_feature: true

preencoder: linear
preencoder_conf:
    input_size: 1024  # Note: If the upstream is changed, please change this value accordingly.
    output_size: 80
```
然后修改 `encoder_conf.input_layer` 为 `conv2d2`，如
```
encoder_conf:
    input_layer: conv2d2 # encoder architecture type
```
进行训练。
